### ISSUE TITLE
AsyncStorage is undefined

### ISSUE THREAD

**Issue by matziol** [0xClpz/i18next-react-native-async-storage#7]
When using package I noticed that language is not persisted in async storage.
I investigated a problem a little and placing `console.error` in [index.js](../blob/master/index.js) Line 44 produces: 
```error
Cannot read properties of undefined (reading 'setItem')
at node_modules/i18next-react-native-async-storage/index.js:42:27 in cacheUserLanguage
```
Going on I placed another console.error in `requireIfAvailable` function at line 6 and this produced:
```
Dynamic require defined at line 4; not supported by Metro
at node_modules/i18next-react-native-async-storage/index.js:4:6 in requireIfAvailable
```
So it seems to be connected with https://github.com/facebook/metro/issues/52

I fixed this on my project with patch-package by removing `requireIfAvailable` function and just require `@react-native-async-storage/async-storage` as I use this package in my project, but I'm not sure how to fix this to support deprecated async storage packages

**Comment by mikaoelitiana** [comment]
@matziol would you mind sharing your patch file or create a PR please?

**Comment by matziol** [comment]
@mikaoelitiana sure I opened PR #9. If you need quick resolution here's my `i18next-react-native-async-storage+1.0.4.patch`:
```patch
diff --git a/node_modules/i18next-react-native-async-storage/index.js b/node_modules/i18next-react-native-async-storage/index.js
index b41c113..ae80146 100644
--- a/node_modules/i18next-react-native-async-storage/index.js
+++ b/node_modules/i18next-react-native-async-storage/index.js
@@ -1,13 +1,4 @@
-
-function requireIfAvailable (path) {
-  try {
-      return require(path);
-  } catch (e) {
-      return false;
-  }
-}
-
-const AsyncStorage = (requireIfAvailable('@react-native-async-storage/async-storage') || requireIfAvailable('@react-native-community/async-storage') || requireIfAvailable('react-native')).AsyncStorage
+const AsyncStorage = require('@react-native-async-storage/async-storage').default;
 
 function callFallbackIfFunc(fallback, callback){
   if(typeof fallback === 'function'){
@@ -41,7 +32,7 @@ module.exports = exports = function(fallback){
       try {
         await AsyncStorage.setItem('@i18next-async-storage/user-language', language)
       } catch(error){
-
+        console.error(error)
       }
     }
   }

```
